In [10]:
import pandas as pd

In [11]:
data1= pd.read_csv("test.csv")
df1= pd.DataFrame(data1)

In [12]:
data2= pd.read_csv("output.csv")
df2= pd.DataFrame(data2)

# Test Data

In [13]:
df1

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,RightClick,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report
0,1,-1,1,1,1,-1,1,1,1,1,...,1,1,1,1,1,-1,-1,1,1,1
1,-1,-1,-1,1,-1,1,1,1,-1,1,...,1,1,1,-1,-1,1,1,-1,1,1
2,-1,-1,-1,1,-1,-1,0,0,1,1,...,1,1,1,1,1,-1,-1,1,0,1
3,-1,-1,1,1,1,-1,1,1,1,1,...,1,1,1,1,1,1,-1,1,1,1
4,1,1,1,1,1,-1,0,-1,-1,1,...,1,1,1,-1,1,1,-1,1,0,1
5,1,-1,1,1,1,1,0,-1,-1,1,...,1,1,1,1,1,1,-1,1,0,1
6,1,1,1,1,1,-1,0,1,-1,-1,...,1,-1,1,-1,1,1,-1,1,0,1
7,1,-1,1,1,1,-1,-1,-1,1,1,...,1,1,1,-1,-1,-1,-1,1,0,1
8,1,-1,1,-1,1,-1,-1,1,1,-1,...,1,-1,-1,1,1,1,-1,1,0,1
9,1,1,1,1,1,-1,0,-1,-1,1,...,1,1,1,-1,-1,-1,-1,1,0,1
10,1,-1,1,1,1,-1,-1,1,1,1,...,1,1,1,1,1,1,-1,1,0,1
11,-1,1,-1,1,1,-1,0,1,-1,1,...,1,1,1,1,1,1,-1,1,0,1

# Output

In [14]:
df2

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,prediction
0,1,-1,1,1,1,-1,1,1,1,1,...,1,1,1,1,-1,-1,1,1,1,1.0
1,-1,-1,-1,1,-1,1,1,1,-1,1,...,1,1,-1,-1,1,1,-1,1,1,1.0
2,-1,-1,-1,1,-1,-1,0,0,1,1,...,1,1,1,1,-1,-1,1,0,1,0.0
3,-1,-1,1,1,1,-1,1,1,1,1,...,1,1,1,1,1,-1,1,1,1,1.0
4,1,1,1,1,1,-1,0,-1,-1,1,...,1,1,-1,1,1,-1,1,0,1,1.0
5,1,-1,1,1,1,1,0,-1,-1,1,...,1,1,1,1,1,-1,1,0,1,1.0
6,1,1,1,1,1,-1,0,1,-1,-1,...,-1,1,-1,1,1,-1,1,0,1,1.0
7,1,-1,1,1,1,-1,-1,-1,1,1,...,1,1,-1,-1,-1,-1,1,0,1,0.0
8,1,-1,1,-1,1,-1,-1,1,1,-1,...,-1,-1,1,1,1,-1,1,0,1,1.0
9,1,1,1,1,1,-1,0,-1,-1,1,...,1,1,-1,-1,-1,-1,1,0,1,0.0
10,1,-1,1,1,1,-1,-1,1,1,1,...,1,1,1,1,1,-1,1,0,1,1.0
11,-1,1,-1,1,1,-1,0,1,-1,1,...,1,1,1,1,1,-1,1,0,1,0.0